/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simple.web.browser;

import java.awt.*;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.Scanner;

public class App {
//    public String getGreeting() {
//        return "Hello world.";
//    }

    public static void main(String[] args) {
        Scanner userInput = new Scanner(System.in);

        System.out.println("============== Simple Web Browser ==============");
        System.out.println("Silahkan pilih menu :\n1. Buka web dengan link\n2. Lihat list \n3. Download file contoh \n4. Download file parallel");

        int chosenNumber = userInput.nextInt();
        switch (chosenNumber) {
            case 1:
                Scanner userLink = new Scanner(System.in);
                System.out.println("Silahkan masukkan link yang ingin dibuka : ");
                String link = userLink.nextLine();
//                System.out.println(link);
                try {
                    openWebpage(new URI(link));
                } catch (URISyntaxException e) {
                    e.printStackTrace();
                }
                break;
            case 2:
                System.out.println("Berikut list link yang dapat dibuka : ");
                System.out.println("1. http://google.com \n2. http://stackoverflow.com \n3. http://facebook.com");
                break;
            default:
                System.out.println("Input tidak valid");
                break;
        }
    }

    public static boolean openWebpage(URI uri) {
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                desktop.browse(uri);
                return true;
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        return false;
    }

    public static boolean openWebpage(URL url) {
        try {
            return openWebpage(url.toURI());
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
        return false;
    }
}
